[workspace]
authors = ["cristianooo <cristi_iorga02@yahoo.com>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "jazzy_ros2_robostack"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-turtlesim = ">=1.8.3,<2"
ros-jazzy-rviz2 = ">=14.1.12,<15"
ros-jazzy-desktop-full = ">=0.11.0,<0.12"
ros-jazzy-rmw-cyclonedds-cpp = ">=2.2.3,<3"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=80.9.0,<81"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-xacro = ">=2.0.13,<3"
ros-jazzy-ros-gz-bridge = ">=1.0.16,<2"
ros-jazzy-ros-gz-sim = ">=1.0.16,<2"
ros-jazzy-ros-gz-image = ">=1.0.16,<2"
ros-jazzy-ros-gz-interfaces = ">=1.0.16,<2"
ros-jazzy-slam-toolbox = ">=2.8.3,<3"
ros-jazzy-nav2-bringup = ">=1.3.7,<2"
ros-jazzy-navigation2 = ">=1.3.7,<2"
ros-jazzy-joint-state-publisher-gui = ">=2.4.0,<3"
ros-jazzy-ros2-control = ">=4.33.0,<5"
ros-jazzy-ros2-controllers = ">=4.28.0,<5"
filelock = ">=3.19.1,<4"
ros-jazzy-gz-ros2-control = ">=1.2.14,<2"
ros-jazzy-gz-ros2-control-demos = ">=1.2.14,<2"
ros-jazzy-python-orocos-kdl-vendor = ">=0.5.1,<0.6"
ros-jazzy-orocos-kdl-vendor = ">=0.5.1,<0.6"
ros-jazzy-kinematics-interface-kdl = ">=1.4.0,<2"
ros-jazzy-kdl-parser = ">=2.11.0,<3"
ros-jazzy-urdf-parser-plugin = ">=2.10.0,<3"
ros-jazzy-tf2-kdl = ">=0.36.12,<0.37"
